platform :ios, '13.0'

target 'Flash Chat iOS13' do
  
  # Pods for Flash Chat iOS13
  # cocoapods >= 1.9.0
use_frameworks! :linkage => :dynamic
  
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'

end
